
develop:
  MY_BRANCH: "develop"
  NAMESPACE: "hr-dev"
  KUBECONFIG: "hr-dev-kubeconfig"
  VALUE_YAML_FILE: "values_dev.yaml"

release:
  MY_BRANCH: "release"
  NAMESPACE: "hr-sit"
  KUBECONFIG: "hr-sit-kubeconfig"
  VALUE_YAML_FILE: "values_release.yaml"

preprod:
  MY_BRANCH: "preprod"
  NAMESPACE: "hr-preprod"
  KUBECONFIG: "hr-preprod-kubeconfig"
  VALUE_YAML_FILE: "values_preprod.yaml"

prod:
  MY_BRANCH: "main"
  NAMESPACE: "app-staging"
  KUBECONFIG: "staging-kubeconfig-2"
  VALUE_YAML_FILE: "values_prod.yaml"
