# generic_config.yaml

PROJECT_URL: "git.qeema.io/qeema-platform/pipeline-demo.git"
REPOSITORY: "registry.tools.idp.qeema.io"
SERVICE_NAME: "pipelinedemo-service"
SONAR_TOKEN: credentials('JENKINS_SONAR_TOKEN_USER')
SONAR_URL: "https://qplatform.dev.qeema.io/sonarqube"
MY_BRANCH: "develop"
PROJECT_KEY: "${env.SERVICE_NAME}-${MY_BRANCH}"
IMAGE: "pipelinedemo-service"

# Add more configuration options as needed...