# generic_config.yaml

pipelinedemo:
  PROJECT_URL: "git.qeema.io/qeema-platform/pipeline-demo.git"
  REPOSITORY: "registry.tools.idp.qeema.io"
  SERVICE_NAME: "pipelinedemo-service"
  SONAR_TOKEN_ID: 'JENKINS_SONAR_TOKEN_USER'
  SONAR_URL: "https://qplatform.dev.qeema.io/sonarqube"
  IMAGE: "pipelinedemo-service"

pipelinedemo_2:
  PROJECT_URL: "git.qeema.io/qeema-platform/pipeline-demo.git"
  REPOSITORY: "registry.tools.idp.qeema.io"
  SERVICE_NAME: "pipelinedemo-service"
  SONAR_TOKEN: credentials('JENKINS_SONAR_TOKEN_USER')
  SONAR_URL: "https://qplatform.dev.qeema.io/sonarqube"
  IMAGE: "pipelinedemo-service"

# Add more configuration options as needed...